create table if not exists public.eventos_tracking (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  nombre_evento text not null,
  cultivo text,
  canal text not null default 'directo',
  datos_adicionales jsonb not null default '{}'::jsonb,
  fecha_evento timestamptz not null default now()
);

alter table public.eventos_tracking enable row level security;

drop policy if exists "Usuarios insertan sus propios eventos" on public.eventos_tracking;
create policy "Usuarios insertan sus propios eventos"
on public.eventos_tracking
for insert
to authenticated
with check (auth.uid() = usuario_id);

drop policy if exists "Usuarios consultan sus propios eventos" on public.eventos_tracking;
create policy "Usuarios consultan sus propios eventos"
on public.eventos_tracking
for select
to authenticated
using (auth.uid() = usuario_id);
